pipeline {
    agent any
    stages {
        stage('Clone repository') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], 
                userRemoteConfigs: [[url: 'https://github.com/Yashcodes04/PES1UG22AM915_Jenkins.git']]])
            }
        }
        stage('Build') {
            steps {
                build 'PES1UG22AM915-1'
                sh 'g++ your_program.cpp -o output'
    stages {
        stage('Build') {
            steps {
                script {
                    sh 'g++ -o PES1UG22AM915-1 your_program.cpp'
                }
            }
        }
        stage('Test') {
            steps {

                sh './output'

                script {
                    sh './PES1UG22AM915-1'
                }

            }
        }
        stage('Deploy') {
            steps {

                echo 'Deploy'

                echo 'Deploying...'

            }
        }
    }
    post {
        failure {

            error 'Pipeline failed'

            echo 'Pipeline failed'

        }
    }
}
